/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MyImage: typeof import('./src/components/myImage.vue')['default']
    NoticeDialog: typeof import('./src/components/noticeDialog.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutDatePicker: typeof import('@nutui/nutui-taro')['DatePicker']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutMenu: typeof import('@nutui/nutui-taro')['Menu']
    NutMenuItem: typeof import('@nutui/nutui-taro')['MenuItem']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    NutUploader: typeof import('@nutui/nutui-taro')['Uploader']
    PublishDialog: typeof import('./src/components/publishDialog.vue')['default']
  }
}
